### ISSUE TITLE
Front End: Adding inputs

### ISSUE THREAD

**Issue by jarw2** [marinaluchner/lsystem#2]
- Slider 1 to tmax

**Comment by G-Shillcock** [comment]
INPUTS:
- ``alphabet = 'ABC'`` 
      - maybe not user defined.
- ``axiom = 'A-BA+AA'`` 
     - string of characters from alphabet and constants
- ``angle = 60``
     - float in range [0,360]
- ``max_iter = 3`` int in range [1,10]
     - might bug for large iter
- ``reproduction_rules = {'A': 'A-A++A-A', 'B': 'A', 'C': 'A-B'}`` 
     - keys are each character in alphabet, values are strings of characters from alphabet and constants

OUTPUTS:
- `` out_string = 'A-A++A-A-A-A+...' ``
    - string of characters from alphabet and constants

**Comment by mwhitemfldm** [comment]
Restrict user inputs:

Axioms : only accept: A, B, +, -, [ , ]
